/**
 * Easy Track — Style Dictionary Configuration
 *
 * Build pipeline:
 *   node style-dictionary.config.js
 *
 * Outputs:
 *   generated/css/primitives.css          — Primitive tokens as CSS vars (shared, never themed)
 *   generated/css/themes/light.css        — Semantic + component tokens for light theme
 *   generated/css/themes/dark.css         — Semantic + component tokens for dark theme
 *   generated/css/themes/high-contrast.css
 *   generated/css/themes/enterprise.css
 *   generated/ts/tokens.ts                — TypeScript token constants
 *   generated/ts/token-types.ts           — TypeScript union types for token paths
 *   generated/tailwind/tokens.js          — Tailwind-compatible token object
 */

const StyleDictionary = require('style-dictionary')

// ── Custom transforms ─────────────────────────────────────────────────────────

// Convert token name from dot.notation to kebab-case for CSS vars
// e.g. primitive.color.slate.500 → --primitive-color-slate-500
StyleDictionary.registerTransform({
  name: 'name/easytrac/css-var',
  type: 'name',
  transformer: (token) =>
    token.path
      .join('-')
      .replace(/\./g, '-')
      .toLowerCase(),
})

// Resolve value references before output
StyleDictionary.registerTransform({
  name: 'value/easytrac/resolve-refs',
  type: 'value',
  matcher: (token) => typeof token.value === 'string' && token.value.startsWith('{'),
  transformer: (token, options) => {
    // Style Dictionary resolves refs automatically — this is a passthrough
    // for documentation purposes
    return token.value
  },
})

// ── Custom formats ────────────────────────────────────────────────────────────

// CSS variables output with :root selector and optional data-theme selector
StyleDictionary.registerFormat({
  name: 'css/easytrac-variables',
  formatter: ({ dictionary, options }) => {
    const selector = options.selector || ':root'
    const comment  = options.comment  || ''
    const vars = dictionary.allTokens
      .map(token => {
        const desc = token.comment || token.description || ''
        const line = `  --${token.name}: ${token.value};`
        return desc ? `  /* ${desc} */\n${line}` : line
      })
      .join('\n')

    return [
      comment && `/* ${comment} */`,
      `${selector} {`,
      vars,
      `}`,
    ].filter(Boolean).join('\n')
  },
})

// TypeScript constants output
StyleDictionary.registerFormat({
  name: 'ts/easytrac-constants',
  formatter: ({ dictionary }) => {
    const entries = dictionary.allTokens.map(token => {
      const key   = token.path.map(p => p.replace(/-/g, '_')).join('_').toUpperCase()
      const value = typeof token.value === 'string' ? `"${token.value}"` : token.value
      const desc  = token.description ? ` // ${token.description}` : ''
      return `export const ${key} = ${value} as const;${desc}`
    })
    return [
      '// Auto-generated by Style Dictionary. Do not edit manually.',
      '// Source: packages/design-tokens/',
      '',
      ...entries,
    ].join('\n')
  },
})

// TypeScript token path union type
StyleDictionary.registerFormat({
  name: 'ts/easytrac-types',
  formatter: ({ dictionary }) => {
    const paths = dictionary.allTokens
      .map(token => `  | '${token.path.join('.')}'`)
      .join('\n')
    return [
      '// Auto-generated by Style Dictionary. Do not edit manually.',
      '',
      'export type TokenPath =',
      paths,
      '',
      'export type ColorToken = Extract<TokenPath, `${string}color${string}`>',
      'export type SpacingToken = Extract<TokenPath, `${string}spacing${string}`>',
      'export type RadiusToken = Extract<TokenPath, `${string}radius${string}`>',
    ].join('\n')
  },
})

// Tailwind JS config object
StyleDictionary.registerFormat({
  name: 'js/easytrac-tailwind',
  formatter: ({ dictionary }) => {
    const toNested = (tokens) => {
      const result = {}
      for (const token of tokens) {
        const parts = token.path
        let current = result
        for (let i = 0; i < parts.length - 1; i++) {
          if (!current[parts[i]]) current[parts[i]] = {}
          current = current[parts[i]]
        }
        current[parts[parts.length - 1]] = `var(--${token.name})`
      }
      return result
    }

    return [
      '// Auto-generated by Style Dictionary. Do not edit manually.',
      `module.exports = ${JSON.stringify(toNested(dictionary.allTokens), null, 2)}`,
    ].join('\n')
  },
})

// ── Transform groups ──────────────────────────────────────────────────────────

StyleDictionary.registerTransformGroup({
  name: 'easytrac/css',
  transforms: [
    'attribute/cti',
    'name/easytrac/css-var',
    'color/css',
    'size/px',
  ],
})

StyleDictionary.registerTransformGroup({
  name: 'easytrac/ts',
  transforms: [
    'attribute/cti',
    'name/easytrac/css-var',
    'color/css',
    'size/px',
  ],
})

// ── Config ────────────────────────────────────────────────────────────────────

module.exports = {
  source: ['primitives/**/*.json'],
  platforms: {},
}

// ── Build function — called per theme ─────────────────────────────────────────

function buildTheme(themeName, semanticFile, options = {}) {
  const sd = StyleDictionary.extend({
    source: [
      'primitives/**/*.json',
      semanticFile,
      'components/tokens.json',
    ],
    platforms: {
      css: {
        transformGroup: 'easytrac/css',
        prefix:         '',
        buildPath:      'generated/css/themes/',
        files: [
          {
            destination: `${themeName}.css`,
            format:      'css/easytrac-variables',
            filter:      (token) => !token.filePath.includes('primitives'),
            options: {
              selector: `[data-theme="${themeName}"]`,
              comment:  `Easy Track — ${themeName} theme tokens`,
            },
          },
        ],
      },
    },
  })
  sd.buildAllPlatforms()
}

function buildPrimitives() {
  const sd = StyleDictionary.extend({
    source: ['primitives/**/*.json'],
    platforms: {
      css: {
        transformGroup: 'easytrac/css',
        buildPath: 'generated/css/',
        files: [
          {
            destination: 'primitives.css',
            format:      'css/easytrac-variables',
            options: {
              selector: ':root',
              comment:  'Easy Track — Primitive tokens (immutable, shared across all themes)',
            },
          },
        ],
      },
      ts: {
        transformGroup: 'easytrac/ts',
        buildPath: 'generated/ts/',
        files: [
          {
            destination: 'primitives.ts',
            format:      'ts/easytrac-constants',
          },
        ],
      },
    },
  })
  sd.buildAllPlatforms()
}

function buildTypescript() {
  const sd = StyleDictionary.extend({
    source: [
      'primitives/**/*.json',
      'semantic/light.json',
      'components/tokens.json',
    ],
    platforms: {
      ts: {
        transformGroup: 'easytrac/ts',
        buildPath: 'generated/ts/',
        files: [
          {
            destination: 'tokens.ts',
            format:      'ts/easytrac-constants',
          },
          {
            destination: 'token-types.ts',
            format:      'ts/easytrac-types',
          },
        ],
      },
      tailwind: {
        transformGroup: 'easytrac/ts',
        buildPath: 'generated/tailwind/',
        files: [
          {
            destination: 'tokens.js',
            format:      'js/easytrac-tailwind',
          },
        ],
      },
    },
  })
  sd.buildAllPlatforms()
}

// ── Run build ─────────────────────────────────────────────────────────────────

console.log('Building Easy Track design tokens...\n')

buildPrimitives()
console.log('✓ Primitives')

buildTheme('light',         'semantic/light.json')
console.log('✓ Light theme')

buildTheme('dark',          'semantic/dark.json')
console.log('✓ Dark theme')

buildTypescript()
console.log('✓ TypeScript types')

console.log('\nBuild complete. Output: packages/design-tokens/generated/')
